### ISSUE TITLE
Appdata screenshot issues

### ISSUE THREAD

**Issue by bertob** [flathub/io.frama.tractor.carburetor#13]
This app's metadata meets the [quality guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines) except for two things:
- The UI font on screenshots is not the platform default (Cantarell)
- Screenshots should be tagged with their respective language, currently there are some non-english screenshots showing up with en-US

**Comment by danialbehzadi** [comment]
Hey @bertob 

I already [updated](https://framagit.org/tractor/tractor.frama.io/-/commit/b412c7e62) screenshots with Cantarell fonts. But I need an advice on language tagging. I think I tagged them correctly on [appstream metainfo file](https://framagit.org/tractor/carburetor/-/blob/main/data/metainfo/io.frama.tractor.carburetor.metainfo.xml) and it shows correctly in Debian repo metadata via GNOME Software, but it fails on Flathub. Would you mind taking a look at the file and give a suggestion?

**Comment by razzeee** [comment]
It might just need a rebuild, which we triggered
