### ISSUE TITLE
Simplify appdata summary

### ISSUE THREAD

**Issue by bertob** [flathub/io.frama.tractor.carburetor#14]
The current summary "Anonymous browsing made easy" is not bad, but it'd be even better if it was prhased in the imperative and didn't include a generic adjective like "easy". Maybe it could just be "Browse anonymously"?

**Comment by danialbehzadi** [comment]
Done: https://framagit.org/tractor/carburetor/-/commit/eb2cf3783

**Comment by bertob** [comment]
Thanks! :heart:
