### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/io.frama.tractor.carburetor#26]
Hi. Thanks for making this beautiful app. Unfortunately, it has never worked for me, neither the previous 4.xx version, nor the 5.0. Tested the flatpak on many distros. This report is for Pop!_OS 22.04:

```
flatpak run io.frama.tractor.carburetor
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:782: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:814: FINISHME: support more multi-planar formats with DRM modifiers
```

```

Starting connection…


Dec 16 14:31:03.010 [notice] Tor 0.4.8.12 running on Linux with Libevent 2.1.12-stable, OpenSSL 3.3.2, Zlib 1.3.1, Liblzma 5.6.3, Libzstd 1.5.6 and Glibc 2.40 as libc.


Dec 16 14:31:03.010 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/


Dec 16 14:31:03.010 [notice] Read configuration file "/tmp/tmp7sdcsirm/tractorrc".


Dec 16 14:31:03.012 [notice] Opening Socks listener on 127.0.0.1:9052


Dec 16 14:31:03.012 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9052


Dec 16 14:31:03.012 [notice] Opening DNS listener on 127.0.0.1:9053


Dec 16 14:31:03.012 [notice] Opened DNS listener connection (ready) on 127.0.0.1:9053


Dec 16 14:31:03.012 [notice] Opening HTTP tunnel listener on 127.0.0.1:9080


Dec 16 14:31:03.012 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:9080


Dec 16 14:31:03.012 [notice] Opening Control listener on /home/az/.var/app/io.frama.tractor.carburetor/config/tractor/control.sock


Dec 16 14:31:03.012 [notice] Opened Control listener connection (ready) on /home/az/.var/app/io.frama.tractor.carburetor/config/tractor/control.sock


Dec 16 14:31:03.000 [notice] Parsing GEOIP IPv4 file /app/share/tor/geoip.


Dec 16 14:31:03.000 [notice] Parsing GEOIP IPv6 file /app/share/tor/geoip6.


Dec 16 14:31:03.000 [notice] Bootstrapped 0% (starting): Starting


Dec 16 14:31:03.000 [notice] Starting with guard context "default"


Dec 16 14:31:04.000 [notice] Bootstrapped 5% (conn): Connecting to a relay


Dec 16 14:31:05.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay


Dec 16 14:31:05.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay


Dec 16 14:31:06.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done


Dec 16 14:31:06.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits


Dec 16 14:31:06.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits


Dec 16 14:31:06.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit


Dec 16 14:31:07.000 [notice] Bootstrapped 100% (done): Done


Connected

```

```
$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_NZ.UTF-8
LC_TIME=en_NZ.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_NZ.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_NZ.UTF-8
LC_NAME=en_NZ.UTF-8
LC_ADDRESS=en_NZ.UTF-8
LC_TELEPHONE=en_NZ.UTF-8
LC_MEASUREMENT=en_NZ.UTF-8
LC_IDENTIFICATION=en_NZ.UTF-8
LC_ALL=
```

**Comment by danialbehzadi** [comment]
Hey Rasheed,
It seems working to me.

Can you try this after the connection completed and share the output?

```bash
$ curl icanhazip.com
$ curl -x socks5h://127.0.0.1:9052 icanhazip.com
```

**Comment by RasheedAZ** [comment]
The first line's output is my correct ipv6 address, and the second one's gives an an ipv4 address that is not mine. 

When I change identity, and then run it, it outputs new ones...

**Comment by danialbehzadi** [comment]
So it is working.

The IP addresses that are not yours are for TOR network exit nodes. You just need to set the proxy on your app/system. If you are using GNOME desktop, the "Set Proxy" in Main menu should do it; otherwise use your app/desktop settings to set the proxies shown on the main page of Carburetor.

**Comment by RasheedAZ** [comment]
That's great to hear. Sorry I need a bit more help. This is my Gnome settings window:

![Screenshot from 2024-12-19 16-09-59](https://github.com/user-attachments/assets/dd7e7783-d7c3-4daf-876c-d57f97220652)

Does this look correct?

Do I remove the prefilled part from Ignore Hosts field? 

What about Https proxy, leave as it is?

Thanks.

**Comment by danialbehzadi** [comment]
Just remove the HTTP Proxy and let it use SOCKS only.

**Comment by RasheedAZ** [comment]
Thanks, it's working perfectly now, and that error message doesn't show up. 

I just realised that checking "Set Proxy" does that automatically! 

Maybe you should make it get automatically done when the user presses connect? Or not a good idea?

**Comment by RasheedAZ** [comment]
> I think no app should change the system settings as an opt-out.

Agreed... but then noobs like me may not able able to figure out you're supposed to click "Set Proxy"... so perhaps some guidance on the Carburetor main page or instructions in the Github readme and Flathub listing page could be helpful?

I had this installed for months thinking it wasn't working not knowing that I had to change proxy setting.

**Comment by danialbehzadi** [comment]
I will add an entry in logs for this.

**Comment by danialbehzadi** [comment]
Done: https://framagit.org/tractor/tractor/-/issues/31
